# Generated by Django 6.0.4 on 2026-05-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='currency',
            field=models.CharField(default='UGX', max_length=5),
        ),
        migrations.AddField(
            model_name='student',
            name='mode_of_study',
            field=models.CharField(choices=[('day', 'Day'), ('distance', 'Distance Learning'), ('weekend', 'Weekend')], default='day', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('local', 'Local'), ('international', 'International')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='tuition_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
