# Generated by Django 6.0.4 on 2026-05-01 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_currency_student_mode_of_study_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='nationality',
        ),
    ]
