# Generated by Django 6.0.4 on 2026-05-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='auto_enrolled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cheque', 'Cheque')], default='bank', max_length=20),
        ),
    ]
