# Generated by Django 6.0.4 on 2026-05-01 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_feepayment_auto_enrolled_and_more'),
        ('students', '0003_remove_student_nationality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feepayment',
            name='auto_enrolled',
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='payment_method',
            field=models.CharField(choices=[('bank', 'Bank Transfer'), ('cash', 'Cash'), ('mobile_money', 'Mobile Money')], default='bank', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('stanbic', 'Stanbic Bank'), ('dtb', 'Diamond Trust Bank'), ('uba', 'United Bank for Africa'), ('dfcu', 'DFCU Bank'), ('other', 'Other')], default='stanbic', max_length=20)),
                ('bank_reference', models.CharField(max_length=100)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UGX', max_length=5)),
                ('semester', models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2')], default=1)),
                ('academic_year', models.CharField(default='2025/2026', max_length=10)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_by', models.CharField(blank=True, max_length=100)),
                ('date_verified', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_submissions', to='students.student')),
            ],
        ),
        migrations.AddField(
            model_name='feepayment',
            name='submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='fees.paymentsubmission'),
        ),
    ]
