# Generated by Django 6.0.4 on 2026-05-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_remove_feepayment_auto_enrolled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feepayment',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='paymentsubmission',
            name='semester',
        ),
        migrations.AddField(
            model_name='feepayment',
            name='semester_in_program',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='paymentsubmission',
            name='semester_in_program',
            field=models.IntegerField(default=1),
        ),
    ]
