# Generated by Django 6.0.4 on 2026-05-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('registry', 'Registry Staff'), ('finance', 'Finance Staff'), ('lecturer', 'Lecturer'), ('exam_office', 'Exam Office'), ('student', 'Student')], default='student', max_length=20),
        ),
    ]
