# Generated by Django 6.0.4 on 2026-05-01 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_is_active_enrollment_semester_examdocket_and_more'),
        ('students', '0003_remove_student_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='students.lecturer'),
        ),
    ]
