# Generated by Django 6.0.4 on 2026-05-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_lecturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='examdocket',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='moduleselection',
            name='semester',
        ),
        migrations.AddField(
            model_name='course',
            name='semester_in_program',
            field=models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')], default=1),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='semester_in_program',
            field=models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')], default=1),
        ),
        migrations.AddField(
            model_name='examdocket',
            name='semester_in_program',
            field=models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')], default=1),
        ),
        migrations.AddField(
            model_name='moduleselection',
            name='semester_in_program',
            field=models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')], default=1),
        ),
        migrations.AlterField(
            model_name='examdocket',
            name='status',
            field=models.CharField(default='generated', max_length=20),
        ),
        migrations.AlterField(
            model_name='moduleselection',
            name='mode_of_study',
            field=models.CharField(default='day', max_length=20),
        ),
    ]
